TrajectoryPlannerROS:
  max_vel_x: 0.5
  min_vel_x: 0.2
  max_vel_theta: 1.0
  min_in_place_vel_theta: 1
  escape_vel: -0.5

  acc_lim_theta: 1
  acc_lim_x: 1
  acc_lim_y: 1
  yaw_goal_tolerance: 0.5

  holonomic_robot: true

  dwa: true
  meter_scoring: true
  path_distance_bias: 32
  goal_distance_bias: 24
  occdist_scale: 0.03 
  heading_lookahead: 0.325
  heading_scoring: true
  heading_scoring_timestep: 0.8
  sim_time: 1
  xy_goal_tolerance: 0.23
