
footprint: [[0.22, 0.25], [0.22, -0.25], [-0.22, -0.25], [-0.22, 0.25]]

#robot_radius: ir_of_robot
inflation_radius: 0.012

plugins:
  - {name: obstacles_2d,      type: "costmap_2d::ObstacleLayer"}
  - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}

transform_tolerance: 20.0

obstacles_2d:
  enabled:                true
  origin_z:               0.0    # meters
  z_resolution:           0.02
  combination_method:     1      # 1=max, 0=override
  track_unknown_space:    true   # default space is unknown
  obstacle_range:         3.0    # meters
  raytrace_range:         3.01
  observation_sources: laserscan
  laserscan:
    data_type: LaserScan
    topic: scan_filtered
    sensor_frame: agent1/laser
    # expected_update_rate: 0.05 # VERY conservative, actual is ~700Hz
    #observation_persistence: 0.0
    marking: true
    clearing: true
    max_obstacle_height: 2.0
    min_obstacle_height: -0.4
