global_costmap:
  global_frame: map
  robot_base_frame: agent1/base_link
  update_frequency: 9.0

  inflation_radius: 0.15

  origin_x: -20.0
  origin_y: -20.0
  width: 40.0
  height: 40.0
  resolution: 0.05

  static_map: false
