<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="agent1">
   
    <xacro:property name="robot" value="agent1"/>
    <!-- physical parameters of robot, all in SI (meters, kg) -->
    
    <!-- base dimensions -->
    <xacro:property name="base_mass" value="2.26796" />
    <xacro:property name="base_width" value="0.381" />     <!-- width=y -->
    <xacro:property name="base_length" value="0.381" />    <!-- length=x -->
    <xacro:property name="base_height" value="0.04" />     <!-- height=z -->
    
    <!-- wheel properties -->
    <xacro:property name="wheel_radius" value="0.05" />
    <xacro:property name="wheel_width" value="0.045" />
    
    <!-- differential properties -->
    <xacro:property name="wheel_mass" value="0.45" />
    <xacro:property name="wheelbase" value="0.3048" />
    <xacro:property name="track_width" value="0.3572" />
    <xacro:property name="wheel_offset_x" value="${wheelbase / 2}" />
    <xacro:property name="wheel_offset_y" value="${(base_width / 2) - (wheel_width / 2)}" />
    <xacro:property name="wheel_offset_z" value="-0.03" />
    
    <!-- lidar properties -->
    <xacro:property name="lidar_mass" value="0.830" />
    <xacro:property name="lidar_height" value="0.0408" />
    <xacro:property name="lidar_length" value="0.096" />
    <xacro:property name="lidar_width" value="0.0583" />
    <xacro:property name="lidar_offset_x" value="0.0" />
    <xacro:property name="lidar_offset_y" value="0.0" />
    <xacro:property name="lidar_offset_z" value="${(lidar_height/2) + (base_height/2)}" />
    
    <!-- imu properties -->
    <xacro:property name="imu_offset_x" value="0.0" />
    <xacro:property name="imu_offset_y" value="0.0" />
    <xacro:property name="imu_offset_z" value="0.0" />
    
    <!-- gripper properties --> 
    <xacro:property name="gripper_length" value="0.07"/>
    <xacro:property name="gripper_width"  value="0.0127"/>
    <xacro:property name="gripper_height" value="0.0127"/>
    <!-- gripper a (top and bottom of robot) properties NOTE: These are offset from the JOINT, not base_link -->
    <xacro:property name="gripper_a_offset_x" value="0"/>
    <xacro:property name="gripper_a_offset_y" value="${gripper_length/2 + gripper_width} "/>
    <xacro:property name="gripper_a_offset_z" value="${gripper_height * 2}"/>
    
    <!-- gripper b (sides of robot) properties NOTE: These are offset from the JOINT, not base_link -->
    <xacro:property name="gripper_b_offset_x" value="${gripper_length/2 + gripper_width} "/>
    <xacro:property name="gripper_b_offset_y" value="0"/>
    <xacro:property name="gripper_b_offset_z" value="${gripper_height * 2}"/>
    

    <!--
        Include other xacro files for simulation plugins, Gazebo references, and macros
    -->
    <xacro:include filename="$(find swarm_sim)/models/agent1/model.gazebo" />
    <xacro:include filename="$(find swarm_sim)/models/agent1/model.macro" />

    <!-- 
        objects contained within the gazebo tags are for Gazebo simulation use only, ignored otherwise.
        They use SDF format, rather than URDF format
    -->
    <gazebo>
        <static>false</static>
    </gazebo>
    
    <!-- base link (the box) -->
    <xacro:box_total name="base_link" mass="${base_mass}" width="${base_width}" length="${base_length}" height="${base_height}"/>

    <!-- front left wheel -->
    <xacro:wheel name="front_left_wheel" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}" wheel_mass="${wheel_mass}"/>
    <xacro:wheel_joint name="front_left_wheel" x_offset="${wheel_offset_x}" y_offset="${wheel_offset_y}" z_offset="${wheel_offset_z}" reflect_x="1" reflect_y="1"/>

    <!-- front right wheel -->
    <xacro:wheel name="front_right_wheel" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}" wheel_mass="${wheel_mass}"/>
    <xacro:wheel_joint name="front_right_wheel" x_offset="${wheel_offset_x}" y_offset="${wheel_offset_y}" z_offset="${wheel_offset_z}" reflect_x="1" reflect_y="-1"/>
    
    <!-- back left wheel -->
    <xacro:wheel name="back_left_wheel" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}" wheel_mass="${wheel_mass}"/>
    <xacro:wheel_joint name="back_left_wheel" x_offset="${wheel_offset_x}" y_offset="${wheel_offset_y}" z_offset="${wheel_offset_z}" reflect_x="-1" reflect_y="1"/>
	
    <!-- back right wheel -->
    <xacro:wheel name="back_right_wheel" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}" wheel_mass="${wheel_mass}"/>
    <xacro:wheel_joint name="back_right_wheel" x_offset="${wheel_offset_x}" y_offset="${wheel_offset_y}" z_offset="${wheel_offset_z}" reflect_x="-1" reflect_y="-1"/>
    
    <xacro:gripper_total name="gripper_1a" mass="0.4" length="${gripper_length}" width="${gripper_width}" height="${gripper_height}" r="0" p="0" y="1.5708" xyz=" ${gripper_a_offset_x} -${gripper_a_offset_y} ${gripper_a_offset_z}"/>
    <xacro:gripper_positive_joint name="gripper_1a" x_offset="${base_length/2}" y_offset="${base_width/2}" z_offset="0" reflect_x="1" reflect_y="1"/>
    
    <xacro:gripper_total name="gripper_1b" mass="0.4" length="${gripper_length}" width="${gripper_width}" height="${gripper_height}" r="0" p="0" y="0" xyz=" -${gripper_b_offset_x} ${gripper_b_offset_y} ${gripper_b_offset_z}"/>
    <xacro:gripper_negative_joint name="gripper_1b" x_offset="${base_length/2}" y_offset="${base_width/2}" z_offset="0" reflect_x="1" reflect_y="1"/>
    
    <xacro:gripper_total name="gripper_2a" mass="0.4" length="${gripper_length}" width="${gripper_width}" height="${gripper_height}" r="0" p="0" y="1.5708" xyz=" -${gripper_a_offset_x} ${gripper_a_offset_y} ${gripper_a_offset_z}"/>
    <xacro:gripper_negative_joint name="gripper_2a" x_offset="${base_length/2}" y_offset="${base_width/2}" z_offset="0" reflect_x="1" reflect_y="-1"/>
    
    <xacro:gripper_total name="gripper_2b" mass="0.4" length="${gripper_length}" width="${gripper_width}" height="${gripper_height}" r="0" p="0" y="0" xyz=" -${gripper_b_offset_x} ${gripper_b_offset_y} ${gripper_b_offset_z}"/>
    <xacro:gripper_positive_joint name="gripper_2b" x_offset="${base_length/2}" y_offset="${base_width/2}" z_offset="0" reflect_x="1" reflect_y="-1"/>
    
    <xacro:gripper_total name="gripper_3a" mass="0.4" length="${gripper_length}" width="${gripper_width}" height="${gripper_height}" r="0" p="0" y="1.5708" xyz=" ${gripper_a_offset_x} -${gripper_a_offset_y} ${gripper_a_offset_z}"/>S
    <xacro:gripper_negative_joint name="gripper_3a" x_offset="${base_length/2}" y_offset="${base_width/2}" z_offset="0" reflect_x="-1" reflect_y="1"/>
    
    <xacro:gripper_total name="gripper_3b" mass="0.4" length="${gripper_length}" width="${gripper_width}" height="${gripper_height}" r="0" p="0" y="0" xyz=" ${gripper_b_offset_x} ${gripper_b_offset_y} ${gripper_b_offset_z}"/>
    <xacro:gripper_positive_joint name="gripper_3b" x_offset="${base_length/2}" y_offset="${base_width/2}" z_offset="0" reflect_x="-1" reflect_y="1"/>
    
    <xacro:gripper_total name="gripper_4a" mass="0.4" length="${gripper_length}" width="${gripper_width}" height="${gripper_height}" r="0" p="0" y="1.5708" xyz=" ${gripper_a_offset_x} ${gripper_a_offset_y} ${gripper_a_offset_z}"/>
    <xacro:gripper_positive_joint name="gripper_4a" x_offset="${base_length/2}" y_offset="${base_width/2}" z_offset="0" reflect_x="-1" reflect_y="-1"/>
    
    <xacro:gripper_total name="gripper_4b" mass="0.4" length="${gripper_length}" width="${gripper_width}" height="${gripper_height}" r="0" p="0" y="0" xyz=" ${gripper_b_offset_x} ${gripper_b_offset_y} ${gripper_b_offset_z}"/>
    <xacro:gripper_negative_joint name="gripper_4b" x_offset="${base_length/2}" y_offset="${base_width/2}" z_offset="0" reflect_x="-1" reflect_y="-1"/>
    
    <!--
    <xacro:transmission name="gripper_1a"/>
    <xacro:transmission name="gripper_1b"/>
    <xacro:transmission name="gripper_2a"/>
    <xacro:transmission name="gripper_2b"/>
    <xacro:transmission name="gripper_3a"/>
    <xacro:transmission name="gripper_3b"/>
    <xacro:transmission name="gripper_4a"/>
    <xacro:transmission name="gripper_4b"/>
    -->
    
    <!-- lidar link -->
    <xacro:box_total name="laser" mass="${lidar_mass}" width="${lidar_width}" height="${lidar_height}" length="${lidar_length}"/>
    <joint name="laser_joint" type="fixed">
        <gazebo reference="laser_joint">
        </gazebo>
        <parent link="base_link"/>
        <child link="laser"/>
        <origin xyz="${lidar_offset_x} ${lidar_offset_y} ${lidar_offset_z}" rpy="0 0 0" />
    </joint>

    <!-- imu link -->
    <xacro:box_total name="imu_link" mass="0.05" width="0.01" height="0.01" length="0.01"/>
    <joint name="imu_joint" type="fixed">
        <gazebo reference="imu_joint">
        </gazebo>
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="${imu_offset_x} ${imu_offset_y} ${imu_offset_z}" rpy="0 0 0" />
    </joint>

</robot>
