scan_filter_chain:
- name: shadows
  type: laser_filters/ScanShadowsFilter
  params:
    min_angle: 0
    max_angle: 360
    neighbors: 50
    window: 1


- name: speckle_filter
  type: laser_filters/LaserScanSpeckleFilter
  params:
    filter_type: 1
    max_range: 5
    max_range_difference: 0.0001
    filter_window: 1

